const express = require('express')
require('./model/db')
const app = express()
const bodyParser = require('body-parser')
const insert = require('./routes/api/post')
const getsingledata = require('./routes/api/get')
app.use(bodyParser.urlencoded({extended:true}))
app.use(bodyParser.json())
app.use(insert)
app.use(getsingledata)
app.listen(3000,()=>console.log('server running on port 3000'))